image: alpine/edge
packages:
  - ruby
  - ruby-bundler
  - hut
oauth: pages.sr.ht/PAGES:RW
environment:
  site: aleksrutins.srht.site
tasks:
  - build: |
      cd farthergate.com
      bundle install --path vendor/bundle
      bundle exec ruby build.rb
  - package: |
      cd farthergate.com/_build
      tar -cvz . > ../../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
